### ISSUE TITLE
There is no dot for the acronym of the author's first name.

### ISSUE THREAD

**Issue by QuPepe** [carlobaldassi/LyX_PNAS#2]
Hi,

Nice to see this project. But it seems that the dot (.) for the acronym of the author's first name is lost. For example, it should be B. Clinton, instead of B Clinton. Could you please fix it?

Thanks,
Frank

**Comment by carlobaldassi** [comment]
Sorry, I'm not sure I understand. Are you referring to the bibliography section? In that case I don't think I can do anything, it's their style and it's rendered that way even in the original Overleaf template.

**Comment by QuPepe** [comment]
Hi, yes, I referred to the bibliography section. The bst file you provide seems newer than the one from the PNAS blog (https://blog.pnas.org/pnas-new.bst). Your bst file is the 2019 version. So, I thought you updated the bst file.

Thanks,
Frank

**Comment by carlobaldassi** [comment]
They probably just didn't update the blog link. In any case the final formatting of the published version is up to them, the template is only for preparing drafts, checking the length etc.
